---
- name: Adding Elasticsearch GPG key
  yum_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Installing apt-transport-https
  yum:
    name: apt-transport-https
    state: present

- name: Adding Elasticsearch APT repository
  yum_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Installing Elasticsearch
  yum:
    name: elasticsearch
    update_cache: yes

- name: Configuring Elasticsearch for outside access
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: '^(network.host:)'
    line: 'network.host: 0.0.0.0'

- name: Updating Elasticsearch port
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: '^(http.port:)'
    line: 'http.port: 9200'

- name: Configuring cluster initial master nodes
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: '^(cluster.initial_master_nodes:)'
    line: 'cluster.initial_master_nodes: ["{{ ansible_default_ipv4.address }}"]'

- name: Verifying Elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: Add Kibana APT Repository
  yum_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    update_cache: yes

- name: Import Elasticsearch GPG Key
  yum_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Update YUM Package Cache
  yum:
    update_cache: yes

- name: Install Kibana
  yum:
    name: kibana
    state: present

- name: Start and Enable Kibana Service
  systemd:
    name: kibana
    enabled: yes
    state: started
- name: Add Logstash APT Repository
  yum_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    update_cache: yes

- name: Import Elasticsearch GPG Key
  yum_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Update APT Package Cache
  yum:
    update_cache: yes

- name: Install Logstash
  yum:
    name: logstash
    state: present

- name: Start and Enable Logstash Service
  systemd:
    name: logstash
    enabled: yes
    state: started


- name: Installing Nagios dependencies and libraries
  yum:
    name:
      - autoconf
      - libc6
      - gcc
      - make
      - wget
      - unzip
      - apache2
      - php
      - libapache2-mod-php
      - libgd-dev
      - openssl
      - libssl-dev
      - bc
      - gawk
      - dc
      - build-essential
      - snmp
      - libnet-snmp-perl
      - gettext
      - python3
      - python3-pip
    state: latest

- name: Installing passlib Python package
  pip:
    name: passlib

- name: Creating Nagios path directory
  file:
    path: ~/nagios
    state: directory

- name: Downloading Nagios
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0777

- name: Installing InfluxDB and its dependencies
  yum:
    name:
      - gcc
      - perl
      - wget
      - curl
    state: latest

- name: Install InfluxDB repository key
  yum_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add InfluxDB APT repository
  yum_repository:
    repo: deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install InfluxDB
  yum:
    name: influxdb
    state: present

- name: Start and enable InfluxDB service
  service:
    name: influxdb
    state: started
    enabled: yes

- name: Open InfluxDB port 8086 in the firewall
  ufw:
    rule: allow
    port: 8086
    proto: tcp

- name: Add Grafana YUM Repository
  yum_repository:
    name: Grafana
    description: Grafana RPM Repository
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: 1
    gpgkey: https://packages.grafana.com/gpg.key
    enabled: 1

- name: Install Grafana
  yum:
    name: grafana
    state: present

- name: Start and enable Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Creating Prometheus Directory
  file:
    path: /opt/prometheus
    state: directory

- name: Downloading Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.47.2/prometheus-2.47.2.linux-amd64.tar.gz
    dest: /opt/prometheus/prometheus-2.47.2.linux-amd64.tar.gz

- name: Extracting Prometheus
  unarchive:
    src: /opt/prometheus/prometheus-2.47.2.linux-amd64.tar.gz
    dest: /opt/prometheus
    remote_src: yes

- name: Creating Prometheus User
  user:
    name: prometheus
    system: yes

- name: Start and Enable Prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Installing Apache (HTTPD) and PHP
  yum:
    name:
      - apache2
      - php
      - libapache2-mod-php
    state: latest

- name: Installing MariaDB (MySQL) Server
  yum:
    name: mariadb-server
    state: latest

- name: Starting and enabling Apache (HTTPD) service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Starting and enabling MariaDB (MySQL) service
  service:
    name: mysql
    state: started
    enabled: yes
